eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    url: 'jdbc:h2:mem:testdb'
  application:
    name: SERVIDOR
    
server:
  port: 8888
  
feign:
  client:
    config:
      default:
        connectTimeout: '5000'
        readTimeout: '5000'    

