eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
feign:
  client:
    config:
      default:
        readTimeout: '5000'
        loggerLevel: FULL
    cliente:
      name: Servidor
      uri: /api-cliente  
      get: /get-clientes
      post: /add-cliente
       
server:
  port: 8020
  
spring:
  application:
    name: CLIENT